language: go
go:
  - 1.x
  - 1.6
  - 1.7.x
  - 1.8.x
  - 1.9.x
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sqlite
install:
  - go get github.com/go-gorp/gorp
  - go get github.com/juju/errors
  - go get github.com/stretchr/testify/assert
  - go get github.com/mattn/go-sqlite3
script: make test